### ISSUE TITLE
`nbproject` 目录不应该加到版本库

### ISSUE THREAD

**Issue by overtrue** [andares/adarts#1]
如题，我觉得项目仓库不应该包含 IDE 的文件。:smile:

**Comment by andares** [comment]
这是netbeans推荐方案，netbeans的项目文件分为公用和私有（nbproject/private）两个目录，后者会加到ignore。而公用部分则方便多人间合作，这跟一些库里会有.editconfig类的文件类似。

我觉得这个方案其实还不错，而且多出的文件体积也不大，同时也比较规整，在可控范围内。所以还是保留吧：）

**Comment by overtrue** [comment]
@andares 好吧

**Comment by andares** [comment]
@overtrue 正在用你的socialite，好想吐糟qq接口……QQ加下好友不？

**Comment by overtrue** [comment]
@andares 44294631
