### ISSUE TITLE
用法请教

### ISSUE THREAD

**Issue by winer632** [andares/adarts#2]
请问PHP7的这个库的功能是否和PHP5.6版本的 php-ext-trie-filter 库一样？
假如我有一个号段表NumberSeg.txt，如下所示，然后我有一个号码 18675821234 要最大匹配出来该号码属于哪个号段。
代码是否就这样写就OK了？

![image](https://cloud.githubusercontent.com/assets/4931801/23252907/71ab1f44-f9ed-11e6-96a8-eab8a7a26ec7.png)

**但是执行的时候得到报错**

![image](https://cloud.githubusercontent.com/assets/4931801/23252873/54c0274e-f9ed-11e6-9433-d9e5bf098890.png)

[root@iZ2ze5v27uq0l43djv0opzZ html]# cat NumberSeg.txt 
1775519
1895656
1805517
1815654
186107
1867582
18662
1866315
1330018
1330019
1334418
1334419
14905
14906
14907
14908
14909
149100
149101
149102
149103
149104
1771764
1812103
1812101
1772100
1772101
1772102
1772103
1772104
1772105
1772106
1772107
1772108
1772109
1772110
1772111
1772112
1772113
1772114
1772115
1772116
1772117
1772118
1772119
1772120
1772121
1772122
1772123
1772124
1772125
1772126
1772127
1772128
1772129
1772130
1772131
1772132
1772133
1772134
1772135
1772136
1772137
1772138
1772139
1772140
1772141
1772142
1772143
1772144
1772145
1772146
1772147
1772148
1772149
1774970
1774971
1774972
1774973
1774974
1774975
1774976
1774977
1774978
1774979
1801884
1812104
1811725
1811633
1814977
1811645
1801646
1561172
189016
189017
189018
189019
18916
18917
18918
18930
189397
189398
189399
18964
10649000
10649001
10649002
10649003
10649062
10649063
10649064
10649065
10649066
10649067
177016
177017
177018
177021
177170
177172
177173
177174
177175
177176
177178
177210
177211
177212
177213
177214
177497
180016
180017
180018
180019
180160
180162
180163
180164
18017
180185
180186
180188
180190
180191
180192
180193
180194
180197
180210
180497
180498
180499
1810005
1810006
1810007
1810008
1810009
181016
181017
181018
181019
181160
181161
181162
181163
181164
181170
181171
181172
181173
181174
181175
181210
181211
181212
181213
181214
181497
133016
133017
133018
133019
133100
133101
133116
133117
133118
133119
133218
133219
133318
133319
133416
133417
133418
133419
133618
133619
133700
133702
133718
133719
133815
133816
133817
133818
133819
133860
133861
133862
133910
133911
133912
133913
133914
153004
153005
153006
153007
153008
153009
153016
153017
153018
153019
15316
15317
153402
1700005
1700006
1700007
1700008
1700009
170016
170017
1700182
1700183
1700184
1700185
170021
1700461
1700462
1700463
1700464
1700490
1700491
1700492
170117
170118
170119
133022
1330230
1330232
1330233
1330238
1330239
1330240
1330249
1331088
1331089
133128
133160
133161
133162
133187
133188
1332280
1332281
133264
133328
133428
133528
1337844
1337845
1337846
1337867
1337868
1337869
133800
1339210
1339211
1339212
1339213
1339214
1339245
1339246
1339247
1339248
1339249
133926
153022
1530235
1530236
1530237
1530238
1530239
1530245
1530246
1530247
1530248
1530249
153220
153222
153223
153233
1533784
1533805
1533806
1533807
1533808
1533809
1534471
1534472
1534740
1534741
1534742
1534743
1534744
189022
1890230
1890232
1890233
1890238
1890239
1890240
1890249
1890300
1890301
1890305
1890306
1890307
189221
189222
189223
189224
189227
1892309
189240
189241
189242
1892430
1892431
1892432
189250
189251
189261
189262
189275
189287
189288
189289
189295
189888
189889
189982
189983
189984
1899867
1899868
189988
173020
173021
1730661
1730664
1730665
1730666
1730667
1730669
173210
173222
177019
177020
1772220
1772226
1772228
1772285
1772286
1772287
1772288
1772289
1772400
1772401
1772402
1772403
1772404
177242
1772435
1772436
1772450
1772451
1772452
1772455
177276
1772775
1772776
1772802
1772803
1772804
1772805
1772806
1772807
1772808
1772809
177281
177651
1776524
1776525
1776526
1776527
1778870
1778871
180022
180117
180118
180119
180223
180224
1802285
1802286
1802287
1802288
1802289
1802345
1802346
1802347
1802348
1802349
180240
180245
1802466
180262
180263
1802640
1802641
1802642
1802643
1802644
180271
180272
180273
180274
180280
180285
180286
180288
180542
180788
1810020
1810021
1801788
1810022
181022
181025
181026
181027
1810280
1810281
1810282
1810283
1810284
1812200
1812201
1812202
1812203
1812204
181221
181222
181223
181224
181227
181242
1812490
1812491
1812492
1812493
1812494
181267
181268
1812740
1812741
1812742
1812743
1812744
181278
181279
181387
181428
181448
1814570
1814571
1814572
1814573
1814574
1814575
1814576
1814860
1814861
1814862
1814863
1814864
181487
181489
1818880
1818884
1818888
1819885
1819886
1819887
1819888
1819889
181989
1890088
1336000
1336001
1336002
1336003
1336004
1336055
1336057
1336058
1336059
1533788
153600
153604
153605
153606
153608
1536125
1536126
1536127
1536128
1536129
1536175
1536176
1536177
1536178
1536179
153740
153844
1700014
1700015
1700016
1700017
1700020
1700021
1700022
1700194
1700195
1700196
1700197
1700198
170020
1700268
1700269
1700300
1700402
1700403
1700486
1700487
1700488
1700489
1700496
1700497
1700692
1700699
1700880
1700881
1700882
1700883
1700884
1701723
1701724
1701725
1701726
1701727
1701728
1701729
170173
1701740
1701741
1701742
149110
10649007
106490080
106490081
106490082
106490085
106490089
106490090
1300020
1300021
1300022
1300023
1300024
130021
130031
130032
130041
1301000
1301031
130128
130201
130202
130221
130231
130232
130241
130321
130406
130416
130421
130441
130446
130456
130466
13056
13052
130616
130617
130618
130619
130626
130627
130628
130721
131205
131206
131207
131208
131209
13122
131248
131275
131276
131277
131278
131279
131481
13162
131660
131661
131662
131663
131664
131670
131671
131672
132480
132481
132482
132483
132622
132625
132626
132627
132628
132629
132960
132961
132962
156016
156017
156018
156019
15618
156921
186016
186017
186021
1861000
1860110
131480
131482
145056
145057
145066
145067
145068
145069
14507
145087
145088
145089
145206
145207
145306
145307
145316
145317
145318
145325
145326
145406
145407
145408
145409
145491
145492
145713
1457140
1457150
1457160
155021
155016
170912
170913
170914
170917
170918
170919
170921
170713
170721
170777
170808
170813
170814
170817
170821
1750160
1750210
1751210
176012
176013
176021
176121
176210
176211
176212
1762130
1762140
1762150
1762160
185016
185017
185021
185160
185161
185162
185163
185164
185165
185166
185167
18521
18616
18621
186442
186443
186444
186445
186446
186544
186844
1730172
1533770
1533771
1700641
1700642
1700668
1700669
1701240
1701249
1700817
1700818
1700819
1700845
1700846
1700847
1700848
1700849
1700965
1700966
1700967
1700968
1700969
1702270
1702271
1702272
1702273
1702274
1702275
1810012
1810013
1810014
1810015
1810016
1810017
1810019
1700832
1700833
1700834
1700835
1700836
1700837
1700838
1700839
1700976
1700973
1700979
1700975
1700977
1700978
1700972
1700974
1700995
1700992
1700996
1700998
1700997
1700994
1700999
1700993
1701250
1701251
1701252
1701253
1701254
1701255
1701256
1701257
1533760
1533761
1533762
1533763
1533765
1533766
1533767
1533768
1533769
1700565
1700568
1700561
1700566
1700567
1700563
1700562
1700564
1700560
133057
133058
133065
133066
133067
133068
133257
133258
133259
133260
133261
133357
133358
133359
133360
133361
133366
133367
133368
133369
133457
133458
133459
133460
133461
133533
133557
133558
133559
133560
133561
133570
133571
133575
133576
13362
133723
133724
133725
133738
133757
133758
133768
133857
133858
133865
133866
133884
133885
133886
133957
133958
133965
133966
133967
133968
133969
153057
153058
153065
153066
153067
153068
153145
153146
153147
153148
153149
15325
153365
153366
153367
153368
153369
153457
153458
15355
15356
15372
15381
153823
153824
153825
153840
153841
153942
153943
153957
153958
153970
153971
153972
153973
153974
153975
170057
170058
170067
170068
170120
170121
170122
170123
170221
170222
170223
170224
170225
170226
170257
173057
173058
173064
173065
173067
173068
173260
173267
173288
173362
173367
173384
173385
173420
173468
17357
173635
173645
173670
173671
173672
173673
173695
173696
173697
173698
173699
173740
173741
173742
173765
173776
177057
177058
177064
177065
177066
177067
177068
177420
177468
17757
177580
177581
177582
177583
177645
177670
177671
177672
177673
177695
177696
177697
177698
177699
177727
177740
177741
177742
177885
177945
177946
180057
180058
180065
180066
180067
180068
180420
180421
180422
180423
180424
180425
18057
18058
180647
180662
180663
180664
18067
18069
18072
180740
180741
180742
180945
180946
180947
181057
181058
181065
181066
181067
181068
181420
181434
18157
181580
181581
181582
181583
181584
181585
181586
181587
181645
181670
181671
181672
181673
189057
189058
189065
189066
189067
189068
18957
18958
189660
189661
189662
189663
189664
18967
18968
18969
189893
189894
189895
189896
189897
189898
177408
177179
173017
173018
173016
173172
173213
173212
173211
173171
173214
173176
173179
173173
[root@iZ2ze5v27uq0l43djv0opzZ html]#

**开发环境是**
[root@iZ2ze5v27uq0l43djv0opzZ html]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@iZ2ze5v27uq0l43djv0opzZ html]# 
[root@iZ2ze5v27uq0l43djv0opzZ html]# php -v
PHP 7.1.2 (cli) (built: Feb 22 2017 12:23:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
[root@iZ2ze5v27uq0l43djv0opzZ html]# 

急盼回复！

**Comment by andares** [comment]
这个库跟你说的扩展完全没关系，请完整读一下readme，跟着里面做就行了。

基本流程就是先构建词典，然后匹配。同时提供了缓存词典功能免除每次构建的时间消耗。

另外看了你的需求好像跟这个库实现的功能有点出入。你是要匹配最大接近号段，这个只是检查一段文本内是否有完整匹配某个词库中的词，如果不是完整匹配返回的是null。

这个不完整匹配的需求，我会考虑在之后版本中加入。

**Comment by daisanmu** [comment]
666

**Comment by winer632** [comment]
如果有可能请尽快加入最大匹配算法，项目急用。谢谢！以前的PHP5环境下的php-ext-trie-filter 库不支持PHP7。做好了你就是独家。。。

**Comment by andares** [comment]
看了下不太好处理，这个需求和这个库的设计目标不同。因加入了失败指针，匹配失败后不是返回而是直接跳转继续前进。而且这个所谓的最大匹配的概念，更接近业务层需求而不是算法需求。

相关的情况你可以查下AC自动机的资料。

**Comment by winer632** [comment]
https://github.com/the-strain/trie

php实现的trie树，可以不用PHP扩展直接实现最大匹配。等不及了，只好自己写一个。。
