### ISSUE TITLE
在已有的字典中新增词汇会出现异常

### ISSUE THREAD

**Issue by imRainChen** [andares/adarts#3]
字典添加并confirm后，再次添加词汇会报出警告
代码测试如下：
```
$dictionary = new \Adarts\Dictionary();
$dictionary->add('钱');
$dictionary->add('测试');
$dictionary->confirm();
$keywords = [];
foreach ($dictionary->seek('钱很多测试') as $result) {
    $keywords[] = $dictionary->getWordByState($result);
}


$dictionary->add('走起');
// 当上面confirm后，再添加再confirm会出现
// PHP Notice:  Undefined offset: 7 
$dictionary->confirm();
$keywords = [];
foreach ($dictionary->seek('钱很多测试走起拉') as $result) {
    $keywords[] = $dictionary->getWordByState($result);
}
```

**Comment by andares** [comment]
收到，我一会儿测试一下。

**Comment by andares** [comment]
是这样，当执行```confirm()```的时候，其实是会有一步把填入的数据压缩成双数组结构，之后再做分析的过程。在目前的算法下，一切的优化是以效率为准则进行处理的，所以重复confirm会出现报错。

当然一个解决方法是在confirm的时候清掉之前的数据重算，但这样的话和重新new一个对象没什么区别了。

这个库的主要作用，也就是生成后的字典，本质上是一份为快速搜索匹配做优化的库，不应该将其作为“原始字典”使用，原始字典更适合放在其他地方，比如数据库、缓存或文件系统里。当需要生成darts树的时候一次性生成。

因为生成字典本身是个高成本的行为，实时生成字典当然可以使用，但效率肯定高不到哪里去。因此比较好的使用方法，还是在某个地方尽量一次性生成字典，之后取出来单纯进行搜索。

如果有特别的需要，可以再做一个类容纳原始字典，并在其中调用此库来实现，会更加好一些。

我会在说明中加上这部分的说明，这个错误暂时不做处理。
